name: chatter_box_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  flutter_bloc: ^9.1.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  path: ^1.9.0
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  meta: ^1.16.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatars/

  fonts:

    - family: Dubai
      fonts:
        - asset: assets/fonts/Dubai/Dubai-Regular.ttf
        - asset: assets/fonts/Dubai/Dubai-Light.ttf
        - asset: assets/fonts/Dubai/Dubai-Medium.ttf
        - asset: assets/fonts/Dubai/Dubai-Bold.ttf
